stages:
  test_stage_1:
    cmd: python3 test_1.py
    deps:
      - test_1.py
    metrics:
      - reports/params_1.json:
          cache: false
    outs:
      - data/test_1.csv

  test_stage_2:
    cmd: python3 test_2.py
    deps:
      - test_2.py
    metrics:
      - reports/params_2.json:
          cache: false
    outs:
      - data/test_2.csv
